### ISSUE TITLE
FW change instead of HW for the PT100

### ISSUE THREAD

**Issue by totoantibes** [LeBassiste/Marlin-2.0.5.3-SKR-V1.4-Turbo-UM2Plus#1]
As i am looking to swap my ultimaker 2.14 board i a have more of a question than an Issue:
instead of replicating the ultimaker preamp circuit for the PT100 is it not possible to play with the  configuration.h thermal settings with 

`#define TEMP_SENSOR_0  -5 //: MAX31865 with Pt100/Pt1000, 2, 3, or 4-wire  (only for sensors 0-1)
// Resistor values when using MAX31865 sensors (-5) on TEMP_SENSOR_0 / 1
#if TEMP_SENSOR_IS_MAX_TC(0)
  #define MAX31865_SENSOR_OHMS_0      100 // (Ω) Typically 100 or 1000 (PT100 or PT1000)
  #define MAX31865_CALIBRATION_OHMS_0 430 // (Ω) Typically 430 for Adafruit PT100; 4300 for Adafruit PT1000
#endif`

thanks

**Comment by LeBassiste** [comment]
you didn't mention what new board exactly you are planning to use instead of the original ultimaker 2.14 board.  if the new board has a MAX31865, then the above configuration may work. if the new board does not have the MAX31865, then it will defo not work.  note that the MAX31865 is an external ADC that interfaces to the board's processor via I2C (or TWI for that matter), whereas:
1. the original ultimaker board uses the internal ADC of its processor to read amplified temp values from the printer's PT100 sensor and has the required pramplifier built in. 
2. if you are planning to use a board that was originally intended to be used with NTC sensors (as opposed to PT100 sensors) on its internal ADC, the you must use a preamplifier.

**Comment by totoantibes** [comment]
Thanks for the details. I am planning on using the SKR 1.4 turbo board.

**Comment by hugoboc** [comment]
@totoantibes, I've converted my Ultimaker 2 to an SKR 1.4 Turbo board a few years ago. Feel free to check out my repository, it might be useful to you.

**Comment by totoantibes** [comment]
> @totoantibes, I've converted my Ultimaker 2 to an SKR 1.4 Turbo board a few years ago. Feel free to check out my repository, it might be useful to you.

Thanks. does look in line with my plans. Will continue questions on your repo then
